### ISSUE TITLE
'terminate called without an active exception' when launching a second script using the same credentials on real account

### ISSUE THREAD

**Issue by illi4** [gehtsoft/forex-connect#22]
I am experience an issue with using two (or more) Python scripts connecting to the same trading account. This is not happening for practice accounts. The api fails when I launch a second script as soon as I connect to fxconnect using the same account (run fxcm.login(...)).  

My Python version is 3.6.8, I'm on Ubuntu 18.04.2 LTS. I have tried different releases of forecxonnect (1.6.3 and 1.6.0). 

On 1.6.3 and 1.6.2: 
When I run one script connected to fxcm and launch a second one, the first one fails with the error 'terminate called without an active exception'. 
On 1.6.0: 
When I run one script connected to fxcm and launch a second one, the second one works and the first one just hangs without any error messages.  If I try to cancel it by pressing Ctrl+C, nothing happens. If I launch the first one again in new terminal, it works (but this is still a problem because I need the first one running). So, evey time I launch a new script, the running one fails.

**Comment by ghost** [comment]
Hi illi4
we have single/multiple setting on account level.
single session is the default. which only allow one session working.
looks like it is your case, 
please provide your account number we will take a look.

thanks
Lei

**Comment by illi4** [comment]
My account id is 2705094378. Is it possible to get / change this setting through API or on the website?

**Comment by ghost** [comment]
Hi

yes, you can make a request via myfxcm.com under account setting tab.

thanks
Lei

**Comment by illi4** [comment]
This is it, it works now. However, I would need to check this sessing through code when new accounts are added to my scripts (otherwise, all the running scripts will break if they do not have multi-session setting). Is this possible. If not, could you consider adding a proper exception / error message to the code? Thank you.

**Comment by ghost** [comment]
Hi

I can report to our project management but I am not sure if or when we can implement this.
For now, you can check it via myfxcm.com
You can also provide all your accounts and  ask Vincent in CC to check on our backend.

Best regards
Lei


CFDs are complex instruments and come with a high risk of losing money rapidly due to leverage.

70.24% of retail investor accounts lose money when trading CFDs with this provider.

You should consider whether you understand how CFDs work and whether you can afford to take the high risk of losing your money.

Trading Forex/CFDs on margin carries a high level of risk and may not be suitable for all investors. Leverage can work against you. The products are intended for retail, professional and eligible counterparty clients. Retail clients who maintain account(s) with Forex Capital Markets Limited ("FXCM LTD") could sustain a total loss of deposited funds but are not subject to subsequent payment obligations beyond the deposited funds but professional clients and eligible counterparty clients could sustain losses in excess of deposits. Clients who maintain account(s) with FXCM Australia Pty. Limited (“FXCM AU”), FXCM South Africa (PTY) Ltd (“FXCM ZA”) or FXCM Markets Limited (“FXCM Markets”) could sustain losses in excess of deposits. Prior to trading any products offered by FXCM LTD<https://www.fxcm.com/uk/>, inclusive of all EU branches, FXCM AU<https://www.fxcm.com/au/>, FXCM ZA<https://www.fxcm.com/za/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<https://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.fxcm.com/au/legal/product-disclosure-statements/>, and Terms of Business<https://docs.fxcorporate.com/tob_au_en.pdf>. Our FX and CFD prices are set by us, are not made on an Exchange and are not governed under the Financial Advisory and Intermediary Services Act. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 20 Gresham Street, 4th Floor, London EC2V 7JE, United Kingdom. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. The information provided by FXCM AU is intended for residents of Australia and is not directed at any person in any country or jurisdiction where such distribution or use would be contrary to local law or regulation. Please read the full Terms and Conditions<https://www.fxcm.com/au/legal/terms-conditions/>. FXCM South Africa (PTY) Ltd is an authorized Financial Services Provider and is regulated by the Financial Sector Conduct Authority under FSP No 46534. FXCM Markets Limited ("FXCM Markets") is incorporated in Bermuda as an operating subsidiary within the FXCM group. FXCM Markets is not required to hold any financial services license or authorization in Bermuda to offer its products and services. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.

**Comment by illi4** [comment]
There is still an issue (same issue) if I open more that around 3 sessions in parralel on the same machine for the same account. Is there a hard limit? How can it be increased?

**Comment by fxcm-dhalpert** [comment]
please check/enable multi session from myfxcm.com
